language: scala
sudo: false
scala:
  - 2.12.10
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/coursier
    - $HOME/.gnupg

before_install:
  - bash scripts/setEnvironment.sh;

install:
  - bash scripts/installGnupg.sh;
#  - bash scripts/install.sh;

script:
#  - if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishSnapshot.sh; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishRelease.sh; fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishDoc.sh; fi
