language: scala
sudo: false
scala:
  - 2.12.12
jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
    - "$HOME/.cache/coursier"

before_install:
  - openssl aes-256-cbc -K $encrypted_404964577bd1_key -iv $encrypted_404964577bd1_iv -in all.gpg.enc -out all.gpg -d
  - bash scripts/setEnvironment.sh;

install:
  - if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/install.sh; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/install.sh; fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then sbt +test; fi

script:
  - if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishSnapshot.sh; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishRelease.sh; fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishDoc.sh; fi
