language: scala
sudo: false
scala:
  - 2.12.12
jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
    - "$HOME/.cache/coursier"

before_install:
  - export GITHUB_TOKEN=$GITHUB_TOKEN
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
    scripts/decrypt-keys.sh; fi

install:
  - rvm use 2.6.5 --install --fuzzy
  - gem install jekyll -v 4

script:
  - sbt +test scalafmtCheckAll scalafmtSbtCheck;

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
    scripts/publishMicrosite.sh; fi
